version: '3.4'

services:
  sql.data:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
#requered when access outside docker, i.e. from application not running by docker
    ports: ["5432:5432"]
    volumes:
      - ./data:/var/lib/postgresql/data

  catalog.api:
#   image: eshop/catalog.api:${TAG:-latest}
    image: catalog
    environment: 
      - DB_URL=jdbc:postgresql://sql.data:5432/postgres
    ports: ["8080:8080"]
    depends_on:
      - sql.data

